database: h2
logging:
    level:
        org:
            springframework: INFO
management:
  server:
    servlet:
      context-path: /manage
spring:
    h2:
      console:
        enabled: true
    datasource:
      data: classpath*:db/${database}/data.sql
      schema: classpath*:db/${database}/schema.sql
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./data/demo
      username: sa
      password: password
    jpa:
      hibernate:
            ddl-auto: validate
      database-platform: org.hibernate.dialect.H2Dialect
    messages:
        basename: messages/messages
    profiles:
        active: production
    thymeleaf:
        mode: HTML
